/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: avprobe.i

package avprobe

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
extern void _wrap_Swig_free_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_avprobe_d8c58f966354aa69(swig_intgo arg1);
extern uintptr_t _wrap_Packet_dts_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_Packet_pts_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern swig_intgo _wrap_Packet_streamIndex_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern void _wrap_delete_Packet_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_new_FFPacket_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern void _wrap_delete_FFPacket_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_FFPacket_dts_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_FFPacket_pts_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern swig_intgo _wrap_FFPacket_streamIndex_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern void _wrap_ReadResult_status_set_avprobe_d8c58f966354aa69(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_ReadResult_status_get_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern void _wrap_ReadResult_packet_set_avprobe_d8c58f966354aa69(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ReadResult_packet_get_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_new_ReadResult_avprobe_d8c58f966354aa69(void);
extern void _wrap_delete_ReadResult_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern uintptr_t _wrap_new_Prober_avprobe_d8c58f966354aa69(void);
extern void _wrap_delete_Prober_avprobe_d8c58f966354aa69(uintptr_t arg1);
extern _Bool _wrap_Prober_open_avprobe_d8c58f966354aa69(uintptr_t arg1, swig_type_1 arg2);
extern uintptr_t _wrap_Prober_readNextPacket_avprobe_d8c58f966354aa69(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_avprobe_d8c58f966354aa69(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrPacket uintptr

func (p SwigcptrPacket) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrPacket) SwigIsPacket() {
}

func (arg1 SwigcptrPacket) Dts() (_swig_ret Int64_t) {
	var swig_r Int64_t
	_swig_i_0 := arg1
	swig_r = (Int64_t)(SwigcptrInt64_t(C._wrap_Packet_dts_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrPacket) Pts() (_swig_ret Int64_t) {
	var swig_r Int64_t
	_swig_i_0 := arg1
	swig_r = (Int64_t)(SwigcptrInt64_t(C._wrap_Packet_pts_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrPacket) StreamIndex() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Packet_streamIndex_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func DeletePacket(arg1 Packet) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Packet_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))
}

type Packet interface {
	Swigcptr() uintptr
	SwigIsPacket()
	Dts() (_swig_ret Int64_t)
	Pts() (_swig_ret Int64_t)
	StreamIndex() (_swig_ret int)
}

type SwigcptrFFPacket uintptr

func (p SwigcptrFFPacket) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFFPacket) SwigIsFFPacket() {
}

func NewFFPacket(arg1 AVPacket) (_swig_ret FFPacket) {
	var swig_r FFPacket
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (FFPacket)(SwigcptrFFPacket(C._wrap_new_FFPacket_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteFFPacket(arg1 FFPacket) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_FFPacket_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrFFPacket) Dts() (_swig_ret Int64_t) {
	var swig_r Int64_t
	_swig_i_0 := arg1
	swig_r = (Int64_t)(SwigcptrInt64_t(C._wrap_FFPacket_dts_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFFPacket) Pts() (_swig_ret Int64_t) {
	var swig_r Int64_t
	_swig_i_0 := arg1
	swig_r = (Int64_t)(SwigcptrInt64_t(C._wrap_FFPacket_pts_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFFPacket) StreamIndex() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_FFPacket_streamIndex_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrFFPacket) SwigIsPacket() {
}

func (p SwigcptrFFPacket) SwigGetPacket() Packet {
	return SwigcptrPacket(p.Swigcptr())
}

type FFPacket interface {
	Swigcptr() uintptr
	SwigIsFFPacket()
	Dts() (_swig_ret Int64_t)
	Pts() (_swig_ret Int64_t)
	StreamIndex() (_swig_ret int)
	SwigIsPacket()
	SwigGetPacket() Packet
}

type SwigcptrReadResult uintptr

func (p SwigcptrReadResult) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrReadResult) SwigIsReadResult() {
}

func (arg1 SwigcptrReadResult) SetStatus(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ReadResult_status_set_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrReadResult) GetStatus() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_ReadResult_status_get_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrReadResult) SetPacket(arg2 Packet) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_ReadResult_packet_set_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrReadResult) GetPacket() (_swig_ret Packet) {
	var swig_r Packet
	_swig_i_0 := arg1
	swig_r = (Packet)(SwigcptrPacket(C._wrap_ReadResult_packet_get_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewReadResult() (_swig_ret ReadResult) {
	var swig_r ReadResult
	swig_r = (ReadResult)(SwigcptrReadResult(C._wrap_new_ReadResult_avprobe_d8c58f966354aa69()))
	return swig_r
}

func DeleteReadResult(arg1 ReadResult) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ReadResult_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))
}

type ReadResult interface {
	Swigcptr() uintptr
	SwigIsReadResult()
	SetStatus(arg2 int)
	GetStatus() (_swig_ret int)
	SetPacket(arg2 Packet)
	GetPacket() (_swig_ret Packet)
}

type SwigcptrProber uintptr

func (p SwigcptrProber) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrProber) SwigIsProber() {
}

func NewProber() (_swig_ret Prober) {
	var swig_r Prober
	swig_r = (Prober)(SwigcptrProber(C._wrap_new_Prober_avprobe_d8c58f966354aa69()))
	return swig_r
}

func DeleteProber(arg1 Prober) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Prober_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrProber) Open(arg2 string) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (bool)(C._wrap_Prober_open_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrProber) ReadNextPacket() (_swig_ret ReadResult) {
	var swig_r ReadResult
	_swig_i_0 := arg1
	swig_r = (ReadResult)(SwigcptrReadResult(C._wrap_Prober_readNextPacket_avprobe_d8c58f966354aa69(C.uintptr_t(_swig_i_0))))
	return swig_r
}

type Prober interface {
	Swigcptr() uintptr
	SwigIsProber()
	Open(arg2 string) (_swig_ret bool)
	ReadNextPacket() (_swig_ret ReadResult)
}


type SwigcptrAVPacket uintptr
type AVPacket interface {
	Swigcptr() uintptr;
}
func (p SwigcptrAVPacket) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrInt64_t uintptr
type Int64_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrInt64_t) Swigcptr() uintptr {
	return uintptr(p)
}

